### ISSUE TITLE
tmux config issue

### ISSUE THREAD

**Issue by ghost** [triebelf/dotfiles#1]
The tmux config file you made is working better than anything else I've found.  There is one minor problem I'm having.  Could you help me out?

When I make a text selection, I get some temporary random characters after my mouse cursor.  They don't seem to have any real effect, but it looks bad.  In this example you can see with/without text selection.

I'm using Ubuntu 18.04, gnome3.

![image](https://user-images.githubusercontent.com/49658151/76238537-98ffbc80-61f5-11ea-96dc-364eee46c158.png)

![image](https://user-images.githubusercontent.com/49658151/76238338-5342f400-61f5-11ea-8212-010d0d2dfa59.png)

**Comment by triebelf** [comment]
Hi, good to hear that you like my config! You are the first one to give feedback. I'm using the same config on Ubuntu 18.04 with Gnome 3 and it works fine, without any random characters. I guess it depends on the terminal or shell configuration, I use alacritty and zsh.

1. Do you see the same problem when using a different terminal or shell?
2. Is your system up to date?
3. You have some special encoding or terminal configuration?

Try updating everything or try with plain default config. Sorry this is not very specific.

**Comment by ghost** [comment]
Thank you for responding.  This config is already useful but I'd be really happy if I could fix this little issue.

I see the same problem with every terminal I've tried. I'm currently using bash version `4.4.20(1)-release`. I tried using a blank `.bashrc` file, but there was no change.  I'm using tmux version `2.6-3ubuntu0.2`.

**Comment by triebelf** [comment]
I observed the same issue on Ubuntu with gnome-terminal or terminator. This option seems to fix the issue:
`set-option -s set-clipboard off`
Please fetch the latest version of my tmux config and retry.

**Comment by ghost** [comment]
>  set-option -s set-clipboard off

This works perfect, thank you!

**Comment by ghost** [comment]
Would you mind providing an email address or sending me an email?  I have a tmux question that isn't relevant to this thread.  My email is `mgumley@gmail.com`

**Comment by triebelf** [comment]
Please find my email in the git log author field, I don't want to put it here in comments. Thank you for understanding.
